fix: Ensure stream handlers are throttled in sequence
near/near-lake-framework-js pull request #27
Opened 2023-02-12 23:11 UTC by morgsmccauley

The current implementation of `startStream` calls the stream handler when pushing to the "throttling" `queue`. This executes the `Promise` immediately and does not wait for it's result before executing the next. As the comment in `startStream` explains, this causes many many handlers to executed, not garuanteeing any sequence to execution, and probably being very resource intensive.

This PR defers the execution of stream handlers by wrapping the handler in another function before pushing it to the `queue`. Then when we read from the `queue`, the handler is called and `await`ed. This ensures that handlers are throttled, and executed in order.

2023-02-13 01:41 UTC, morgsmccauley commented
Just realised this is an issue in `main` and should probably be pushed there too 🤔

2023-02-13 13:10 UTC, khorolets approved these changes
This is a great catch! Thank you! Would you mind creating a similar PR for the `main` so we are not pushed to rush with 1.1 version, please?

2023-02-13 15:30 UTC, frol requested changes
This defeats the purpose of the queue. If someone wants to execute in sequence, they should be able to configure the size of the queue (10).

2023-02-16 00:32 UTC, morgsmccauley commented
Thanks for calling this out @frol 

I misunderstood this logic, and didn't realise that 'batching' was desired behaviour. Here's what's actually happening:
1. 10 handlers get pushed to the queue - all 10 are executed at the time they are pushed
2. an 11th handler gets pushed to the queue, in the same loop, we pop the first handler, and `await` its completion
3. Each subsequent loop does the same, push a new handler to the queue, and `await` the first in the queue

Essentially, we have 11 handlers which are executing concurrently, and the first has to complete before adding/executing another.

This PR is not needed, but after discussing with @frol we decided that having a configurable `batch_size` would be beneficial, to allow developers the option of either executing sequentially or in parallel. I'll create another PR for that, which can be included in the `1.1` release.

cc: @khorolets

2023-02-16 00:32 UTC, closed without merging